import re

def string_to_slug(s):
    """
    
    Python version of this js code in select-stats-step-form and other js files
    
    To update this, after running code like: for collection_name in collection, initalize a dict and update it like below
    dummy_dict[string_to_slug(collection_name.split('_')[0])] = collection_name
    
    print contents of new dict and add to title_renaming_dict below
    """
    s = s.strip().lower()

    from_chars = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;"
    to_chars   = "aaaaeeeeiiiioooouuuunc      "
    trans_table = str.maketrans(from_chars, to_chars)
    s = s.translate(trans_table)

    s = re.sub(r'[^a-z0-9 -]', '', s)

    s = re.sub(r'\s+', '_', s)

    return s

title_renaming_dict = {
    "seneca_de_providentia": "Seneca, De Providentia_TEXT",
    "apuleius_florida": "Apuleius, Florida_TEXT",
    "dares_de_excidio_troiae": "Dares, De Excidio Troiae_TEXT",
    "ocr_gsce_defined_vocabulary_list": "OCR GSCE Defined Vocabulary List_LIST",
    "codex_justinianus_on_slavery": "Codex Justinianus (On Slavery)_TEXT",
    "horace_ars_poetica": "Horace, Ars Poetica_TEXT",
    "introduction_to_latin_shelmerdine": "Introduction to Latin (Shelmerdine)_LIST",
    "vergil_georgics": "Vergil, Georgics_TEXT",
    "ecce_romani_chs_1-54": "Ecce Romani (Chs. 1-54)_LIST",
    "claudian_de_consulatu_stilichonis_preface_to_book_3": "Claudian, De Consulatu Stilichonis (Preface to Book 3)_TEXT",
    "seneca_naturales_quaestiones_-_dcc": "Seneca, Naturales Quaestiones - DCC_LOCAL_TEXT",
    "jenney_first_year_latin_purple_jenney-scudder-baade": "Jenney First Year Latin Purple (Jenney-Scudder-Baade)_LIST",
    "bernardo_de_riofrio_centonicum_virgilianum_monimentum": "Bernardo de Riofrio, Centonicum Virgilianum Monimentum_TEXT",
    "vitruvius_book_1": "Vitruvius, Book 1_TEXT",
    "tacitus_germania": "Tacitus, Germania_TEXT",
    "cicero_post_reditum_in_senatu": "Cicero, Post Reditum In Senatu_TEXT",
    "testamentum_porcelli": "Testamentum Porcelli_TEXT",
    "ennodius_carmina_routledge_later_latin_poets": "Ennodius, Carmina (Routledge Later Latin Poets)_TEXT",
    "seneca_de_vita_beata": "Seneca, De Vita Beata",
    "cicero_pro_balbo": "Cicero, Pro Balbo_TEXT",
    "physiologus_latina_1-6_9_16_17_23": "Physiologus Latina (1-6, 9, 16, 17, 23)_TEXT",
    "pliny_the_younger_epistulae_ap_selections": "Pliny the Younger, Epistulae (AP Selections)_TEXT",
    "ilias_latina": "Ilias Latina_TEXT",
    "anthologia_latina_9_r_narcissus_cento": "Anthologia Latina 9 R (Narcissus Cento)_TEXT",
    "elizabeth_jane_weston_addenda_ad_parthenica": "Elizabeth Jane Weston, Addenda ad Parthenica_TEXT",
    "hildegard_of_bingen_scivias_72": "Hildegard of Bingen, Scivias 7.2_TEXT",
    "juvenal_6248-268_feminaeromanaeorg": "Juvenal 6.248-268 (FeminaeRomanae.org)_LOCAL_TEXT",
    "hildegard_of_bingen_ordo_virtutum": "Hildegard of Bingen, Ordo Virtutum_TEXT",
    "seneca_hercules_furens_dcc": "Seneca, Hercules Furens (DCC)_LOCAL_TEXT",
    "egeria_itinerarium_book_1": "Egeria, Itinerarium Book 1_TEXT",
    "maffeius_historiae_indicae_13-5_7-10_27-31_35-39_22-7_53-5_6_all": "Maffeius, Historiae Indicae 1.3-5, 7-10, 27-31, 35-39, 2.2-7, 5.3-5, 6 (all)_TEXT",
    "plautus_curculio": "Plautus, Curculio_TEXT",
    "pliny_the_younger_epistulae": "Pliny the Younger, Epistulae_TEXT",
    "marie_de_france_fables_1-22": "Marie De France, Fables 1-22_TEXT",
    "apuleius_de_mundo": "Apuleius, De Mundo_TEXT",
    "florus_epitome_11_romulus_and_roman_kings": "Florus, Epitome 1.1 (Romulus and Roman Kings)_TEXT",
    "horace_odes_garrison_edition": "Horace, Odes (Garrison Edition)_TEXT",
    "ovid_heroidum_epistulae": "Ovid, Heroidum Epistulae_TEXT",
    "vergil_eclogues_1_dcc": "Vergil, Eclogues 1 (DCC)_LOCAL_TEXT",
    "cicero_de_imperio_cn_pompei": "Cicero, De Imperio Cn Pompei_TEXT",
    "catullus_carmina": "Catullus, Carmina_TEXT",
    "seneca_de_constantia": "Seneca, De Constantia_TEXT",
    "martial_epigrams": "Martial, Epigrams_TEXT",
    "claudian_panegyricus_dictus_manlio_theodoro_consuli": "Claudian, Panegyricus Dictus Manlio Theodoro Consuli_TEXT",
    "apuleius_asclepius": "Apuleius, Asclepius_TEXT",
    "elizabeth_jane_weston_ad_matthiam_secundum": "Elizabeth Jane Weston, Ad Matthiam Secundum_TEXT",
    "newton_regulae_philosophandi": "Newton, Regulae Philosophandi_TEXT",
    "corderius_colloquia_book_2": "Corderius, Colloquia (Book 2)_TEXT",
    "claudian_panegyricus_de_iv_consulatu_honorii_augusti": "Claudian, Panegyricus de IV Consulatu Honorii Augusti",
    "carmina_priapea_1-80": "Carmina Priapea 1-80_TEXT",
    "phaedrus_fables": "Phaedrus, Fables_TEXT",
    "tacitus_agricola_dcc": "Tacitus, Agricola (DCC)_LOCAL_TEXT",
    "oxford_latin_course_balme-morwood": "Oxford Latin Course (Balme-Morwood)_LIST",
    "catullus_carmina_garrison": "Catullus, Carmina (Garrison)_LOCAL_TEXT",
    "horace_carmen_saeculare": "Horace, Carmen Saeculare_TEXT",
    "cicero_pro_ligario": "Cicero, Pro Ligario_TEXT",
    "apuleius_peri_hermeneias": "Apuleius, Peri Hermeneias_TEXT",
    "latin_for_the_new_millennium_vols_1_and_2_tunberg-minkova": "Latin for the New Millennium Vols 1 and 2 (Tunberg-Minkova)_LOCAL_LIST",
    "prudentius_psychomachia": "Prudentius Psychomachia_TEXT",
    "seneca_phoenissae": "Seneca, Phoenissae_TEXT",
    "universal_declaration_of_human_rights": "Universal Declaration of Human Rights_TEXT",
    "abelard_historia_selections": "Abelard, Historia Selections_TEXT",
    "hildegard_of_bingen_letters_70r": "Hildegard of Bingen, Letters 70r_TEXT",
    "newton_axiomata_motus": "Newton, Axiomata Motus_TEXT",
    "claudian_panegyricus_de_vi_consulatu_honorii_augusti_preface": "Claudian, Panegyricus de VI Consulatu Honorii Augusti (Preface)",
    "cicero_post_reditum_ad_quirites": "Cicero, Post Reditum Ad Quirites_TEXT",
    "augustine_confessions_book_1": "Augustine, Confessions (Book 1)_TEXT",
    "38_latin_stories": "38 Latin Stories_TEXT",
    "cicero_philippics": "Cicero, Philippics_TEXT",
    "book_of_thobit": "Book of Thobit_TEXT",
    "cicero_cato_maior_de_senectute": "Cicero, Cato Maior De Senectute_TEXT",
    "latin_an_intensive_course_moreland-fleischer": "Latin An Intensive Course (Moreland-Fleischer)_LIST",
    "horace_epodes": "Horace, Epodes_TEXT",
    "claudian_panegyricus_dictus_manlio_theodoro_consuli_preface": "Claudian, Panegyricus Dictus Manlio Theodoro Consuli (Preface)_TEXT",
    "piantaggini_livia_mater_eloquens": "Piantaggini, Livia Mater Eloquens",
    "pseudo-sallust_invective_against_cicero": "Pseudo-Sallust, Invective Against Cicero_TEXT",
    "sallust_bellum_iugurthinum": "Sallust, Bellum Iugurthinum_TEXT",
    "jerome_life_of_malchus_dcc": "Jerome, Life of Malchus (DCC)_TEXT",
    "ovid_in_ibin": "Ovid, In Ibin_TEXT",
    "plautus_bacchides": "Plautus, Bacchides_TEXT",
    "laudatio_turiae": "Laudatio Turiae_TEXT",
    "owen_epigrams": "Owen, Epigrams_TEXT",
    "elizabeth_jane_weston_de_ebrietate": "Elizabeth Jane Weston, De Ebrietate_TEXT",
    "jenney_first_year_latin_red": "Jenney First Year Latin Red_LIST",
    "oxford_latin_course_for_college_fabulae_all": "Oxford Latin Course for College, Fabulae (all)_TEXT",
    "hirtius_bellum_gallicum_8": "Hirtius, Bellum Gallicum 8_TEXT",
    "pseudo-caesar_bellum_alexandrinum": "Pseudo-Caesar, Bellum Alexandrinum_TEXT",
    "augustus_res_gestae_1": "Augustus, Res Gestae 1",
    "claudian_fescennia": "Claudian, Fescennia_TEXT",
    "cicero_pro_archia": "Cicero, Pro Archia_TEXT",
    "gibbs_brevissima_epigrammata": "Gibbs, Brevissima Epigrammata",
    "new_latin_primer_english-irby": "New Latin Primer (English-Irby)_LIST",
    "civis_romanus_a_reader_for_the_first_two_years_of_latin_cobban_and_colebourn": "Civis Romanus, a Reader for the First Two Years of Latin (Cobban and Colebourn)_TEXT",
    "apuleius_de_platone": "Apuleius, De Platone_TEXT",
    "ocr_gsce_restricted_vocabulary_list": "OCR GSCE Restricted Vocabulary List_LIST",
    "vergil_aeneid": "Vergil, Aeneid_LOCAL_TEXT",
    "cicero_laelius_de_amicitia": "Cicero, Laelius De Amicitia_TEXT",
    "learn_to_read_latin_keller-russell": "Learn to Read Latin (Keller-Russell)_LIST",
    "cicero_de_officiis": "Cicero, De Officiis_TEXT",
    "seneca_de_beneficiis": "Seneca, De Beneficiis_TEXT",
    "seneca_de_otio": "Seneca, De Otio_TEXT",
    "vulgate_relevations": "Vulgate, Relevations_TEXT",
    "anthologia_latina_11_r_iudicium_paridis_cento": "Anthologia Latina 11 R (Iudicium Paridis Cento)_TEXT",
    "horace_satires": "Horace, Satires_TEXT",
    "sallust_bellum_catilinae": "Sallust, Bellum Catilinae_LOCAL_TEXT",
    "claudian_de_bello_gildonico": "Claudian, De Bello Gildonico",
    "cicero_pro_caelio": "Cicero, Pro Caelio_TEXT",
    "claudian_in_eutropium": "Claudian, In Eutropium_TEXT",
    "seneca_oedipus": "Seneca, Oedipus_TEXT",
    "oxford_latin_course_for_college": "Oxford Latin Course for College_LOCAL_LIST",
    "pseudo-caesar_bellum_hispanum": "Pseudo-Caesar, Bellum Hispanum_TEXT",
    "martial_book_10": "Martial, Book 10_TEXT",
    "cicero_de_lege_agraria": "Cicero, De Lege Agraria_TEXT",
    "livy_ab_urbe_condita_ib_list_2_selections": "Livy, Ab Urbe Condita (IB List 2 Selections)_TEXT",
    "seneca_ad_helviam_matrem_de_consolatione": "Seneca, Ad Helviam Matrem De Consolatione_TEXT",
    "hrotswitha_dulcitius": "Hrotswitha, Dulcitius_TEXT",
    "fabulae_faciles_ritchie": "Fabulae Faciles (Ritchie)_TEXT",
    "ap_latin_core_list_2024": "AP Latin Core List 2024_LIST",
    "200_essential_latin_words_list_mahoney": "200 Essential Latin Words List (Mahoney)_LIST",
    "landivar_rusticatio_mexicana_book_6": "Landivar, Rusticatio Mexicana Book 6_TEXT",
    "williams_ursus_et_porcus": "Williams, Ursus et Porcus_TEXT",
    "juvenal_saturae": "Juvenal, Saturae_TEXT",
    "ovid_fasti": "Ovid, Fasti_6.219-234_LOCAL_TEXT",
    "apuleius_de_mundo_pref": "Apuleius, De Mundo Pref_TEXT",
    "claudian_in_eutropium_preface_to_book_2": "Claudian, In Eutropium (Preface to Book 2)_TEXT",
    "vulgate_genesis_1-3": "Vulgate, Genesis 1-3_TEXT",
    "eutropius_breviarium_all": "Eutropius, Breviarium (all)_LOCAL_TEXT",
    "seneca_agamemnon": "Seneca, Agamemnon_TEXT",
    "suetonius_life_of_caligula": "Suetonius, Life of Caligula",
    "tibullus_elegies": "Tibullus, Elegies_TEXT",
    "colby_latin_list_years_1_3_4": "Colby Latin List (Years 1, 3, 4)_LIST",
    "cicero_de_haruspicum_responso": "Cicero, De Haruspicum Responso_TEXT",
    "aesop_romulus_anglicus_1-10": "Aesop (Romulus Anglicus 1-10)_TEXT",
    "cato_monostichs": "Cato, Monostichs_TEXT",
    "elizabeth_jane_weston_carmen_ad_rudolphum_ii": "Elizabeth Jane Weston, Carmen ad Rudolphum II_TEXT",
    "latin_for_americans_vol_1_and_2_ullman-henderson": "Latin for Americans Vol 1 and 2 (Ullman-Henderson)_LIST",
    "cicero_pro_rege_deiotario": "Cicero, Pro Rege Deiotario_TEXT",
    "claudian_epithalamium_de_nuptii_honorii_augusti": "Claudian, Epithalamium de Nuptii Honorii Augusti_TEXT",
    "disce_kitchell-sienkewicz": "Disce (Kitchell-Sienkewicz)_LIST",
    "claudian_de_consulatu_stilichonis": "Claudian, De Consulatu Stilichonis",
    "cicero_pro_sestio": "Cicero, Pro Sestio_TEXT",
    "a_primer_of_ecclesiastical_latin_collins": "A Primer of Ecclesiastical Latin (Collins)_LOCAL_LIST",
    "international_baccalaureate_vocabulary_hl_selections": "International Baccalaureate Vocabulary (HL Selections)",
    "latin_for_the_new_millennium_readings_volume_1_tunberg-minkova": "Latin for the New Millennium Readings, Volume 1 (Tunberg-Minkova)_TEXT",
    "diederich_frequency_list_medieval": "Diederich Frequency List (Medieval)_LIST",
    "seneca_hercules_oetaeus": "Seneca, Hercules Oetaeus_TEXT",
    "seneca_troades": "Seneca, Troades_TEXT",
    "claudian_carminum_minorum_appendix": "Claudian, Carminum Minorum Appendix_TEXT",
    "elizabeth_jane_weston_in_obitum_ioannae": "Elizabeth Jane Weston, In Obitum Ioannae_TEXT",
    "eduqas_gsce_defined_vocablary_list": "Eduqas GSCE Defined Vocablary List_LIST",
    "proba_cento_vergilianus": "Proba, Cento Vergilianus",
    "jenney_first_year_combined": "Jenney First Year Combined_LIST",
    "lingua_latina_per_se_illustrata_pars_i_oerberg": "Lingua Latina Per Se Illustrata, Pars I (Oerberg)_LIST",
    "seneca_ad_marciam_de_consolatione": "Seneca, Ad Marciam De Consolatione_TEXT",
    "hildegard_of_bingen_physica_85": "Hildegard of Bingen, Physica 8.5_TEXT",
    "plautus_asinaria": "Plautus, Asinaria_TEXT",
    "cicero_in_verrem_actio_prima": "Cicero, In Verrem Actio Prima_TEXT",
    "appendix_virgiliana_carmina_priaepea": "Appendix Virgiliana, Carmina Priaepea_TEXT",
    "cicero_in_vatinium": "Cicero, In Vatinium_TEXT",
    "hartnett_by_roman_hands": "Hartnett, By Roman Hands_TEXT",
    "plautus_amphitruo": "Plautus, Amphitruo_TEXT",
    "elizabeth_jane_weston_vota_pro_felicibus_et_secundis_nuptis": "Elizabeth Jane Weston, Vota Pro Felicibus et Secundis Nuptis_TEXT",
    "vergil_eclogues": "Vergil, Eclogues_TEXT",
    "apuleius_de_deo_socratis": "Apuleius, De Deo Socratis_TEXT",
    "international_baccalaureate_vocabulary_sl_hl_selections": "International Baccalaureate Vocabulary (SL & HL Selections)_LIST",
    "persius_satires": "Persius, Satires_TEXT",
    "seneca_ad_polybium_de_consolatione": "Seneca, Ad Polybium De Consolatione_TEXT",
    "caesar_bellum_gallicum": "Caesar, Bellum Gallicum_LOCAL_TEXT",
    "requiem_mass": "Requiem Mass_TEXT",
    "vulgate_genesis_37-43_story_of_joseph": "Vulgate, Genesis 37-43 (Story of Joseph)_TEXT",
    "curtius_history_of_alexander_books_3-10": "Curtius, History of Alexander (Books 3-10)_TEXT",
    "carmina_burana_orff_latin_lyrics_1-5_11-15_17-25": "Carmina Burana (Orff Latin Lyrics 1-5, 11-15, 17-25)_TEXT",
    "diederich_frequency_list_prose": "Diederich Frequency List (Prose)_LIST",
    "cicero_pro_quinctio": "Cicero, Pro Quinctio_TEXT",
    "diederich_frequency_list_general": "Diederich Frequency List (General)_LIST",
    "stabat_mater": "Stabat Mater_TEXT",
    "wheelock_latin_lafleur": "Wheelock Latin (LaFleur)_LIST",
    "livy_ab_urbe_condita_39819_de_bacchanalibus": "Livy, Ab Urbe Condita 39.8–19 (De Bacchanalibus)",
    "cicero_in_calpurnium_pisonem": "Cicero, In Calpurnium Pisonem_TEXT",
    "cicero_pro_rabirio_perduellionis_reo": "Cicero, Pro Rabirio Perduellionis Reo_TEXT",
    "de_romanis_radice": "De Romanis (Radice)_LIST",
    "cicero_pro_sulla": "Cicero, Pro Sulla_TEXT",
    "seneca_apocolocyntosis": "Seneca, Apocolocyntosis_TEXT",
    "tacitus_annales": "Tacitus, Annales_TEXT",
    "florus_epitome_22-23_gracchi": "Florus, Epitome 2.2-2.3 (Gracchi)_TEXT",
    "cicero_pro_roscio_amerino": "Cicero, Pro Roscio Amerino_TEXT",
    "ovid_amores_1_dcc": "Ovid, Amores 1 (DCC)_LOCAL_TEXT",
    "cato_distichs": "Cato, Distichs_TEXT",
    "apollonius_king_of_tyre": "Apollonius, King of Tyre_TEXT",
    "cornelia_epistulae_corneliae_ad_gracchos_fr_1_and_2": "Cornelia, Epistulae Corneliae ad Gracchos (fr. 1 and 2)_TEXT",
    "suburani_volumes_1_2": "Suburani Volumes 1 & 2_LOCAL_LIST",
    "cicero_pro_milone": "Cicero, Pro Milone_TEXT",
    "claudian_epithalamium_de_nuptiis_honorii_augusti_preface": "Claudian, Epithalamium de Nuptiis Honorii Augusti (Preface)_TEXT",
    "claudian_carmina_minora_25_preface": "Claudian, Carmina Minora 25 Preface_TEXT",
    "latin_stopwords_list_cltk": "Latin Stopwords List (CLTK)_LIST",
    "apuleius_metamorphoses_finkelpearl": "Apuleius, Metamorphoses (Finkelpearl)_TEXT",
    "claudian_in_rufinum": "Claudian, In Rufinum_TEXT",
    "claudian_de_raptu_prosperinae_prefaces": "Claudian, De Raptu Prosperinae (Prefaces)_TEXT",
    "claudian_panegyricus_de_iii_consulatu_honorii_augusti_preface": "Claudian, Panegyricus de III Consulatu Honorii Augusti (Preface)_TEXT",
    "tacitus_agricola": "Tacitus, Agricola_TEXT",
    "classical_latin_mckeown": "Classical Latin (McKeown)_LIST",
    "cicero_pro_cluentio": "Cicero, Pro Cluentio_TEXT",
    "cicero_de_domo_sua": "Cicero, De Domo Sua_TEXT",
    "cambridge_latin_course": "Cambridge Latin Course_LIST",
    "getting_started_with_latin_linney": "Getting Started with Latin (Linney)_LIST",
    "ovid_medicamina_faciei_femineae": "Ovid, Medicamina Faciei Femineae_TEXT",
    "wiley_real_latin_maltby-belcher": "Wiley Real Latin (Maltby-Belcher)_LIST",
    "tacitus_dialogus_de_oratoribus": "Tacitus, Dialogus De Oratoribus_TEXT",
    "ovid_remedia_amoris": "Ovid, Remedia Amoris_TEXT",
    "eutropius_breviarium_book_3_beyer": "Eutropius, Breviarium Book 3 (Beyer)_LOCAL_TEXT",
    "florus_epitome_221_cleopatra": "Florus, Epitome 2.21 (Cleopatra)_TEXT",
    "tacitus_historiae": "Tacitus, Historiae_TEXT",
    "ocr_as_level_defined_vocabulary_list": "OCR AS Level Defined Vocabulary List_LIST",
    "seneca_phaedra": "Seneca, Phaedra_TEXT",
    "cato_de_agricultura": "Cato, De Agricultura_TEXT",
    "seneca_de_tranquillitate_animi": "Seneca, De Tranquillitate Animi_TEXT",
    "suburani_fabulae": "Suburani, Fabulae_LOCAL_TEXT",
    "bede_historia_ecclesiastica_gentis_anglorum_prologue_11_125-26_21-2_12-14_16_20_31-3_5-6": "Bede, Historia Ecclesiastica Gentis Anglorum (Prologue, 1.1, 1.25-26, 2.1-2, 12-14, 16, 20, 3.1-3, 5-6)_TEXT",
    "seneca_thyestes": "Seneca, Thyestes_TEXT",
    "cicero_in_toga_candida": "Cicero, In Toga Candida_TEXT",
    "cicero_pro_roscio_comoedo": "Cicero, Pro Roscio Comoedo_TEXT",
    "hyginus_fabulae": "Hyginus, Fabulae_TEXT",
    "ruaeus_aeneid_summaries": "Ruaeus, Aeneid Summaries",
    "claudian_panegyricus_dictus_olybrio_et_probino_consulibus": "Claudian, Panegyricus Dictus Olybrio et Probino Consulibus_TEXT",
    "ovid_metamorphoses_1-6_11_15": "Ovid, Metamorphoses 1-6, 11, 15_TEXT",
    "keep_going_with_latin_linney": "Keep Going with Latin (Linney)_LIST",
    "prudentius_psychomachia_preface": "Prudentius, Psychomachia (Preface)_TEXT",
    "dcc_latin_core": "DCC Latin Core_LOCAL_LIST",
    "cicero_pro_plancio": "Cicero, Pro Plancio_TEXT",
    "elizabeth_jane_weston_ad_schosserum": "Elizabeth Jane Weston, Ad Schosserum_TEXT",
    "seneca_pseudo_proverbia_or_de_moribus": "Seneca, (Pseudo) Proverbia or De Moribus",
    "seneca_de_clementia": "Seneca, De Clementia_all_TEXT",
    "claudian_carmina_minora": "Claudian, Carmina Minora_TEXT",
    "petronius_satyricon": "Petronius, Satyricon_TEXT",
    "nepos_prologue_to_the_lives_of_foreign_generals": "Nepos, Prologue to the Lives of Foreign Generals_TEXT",
    "plautus_casina": "Plautus, Casina_TEXT",
    "ap_latin_core_list_2025": "AP Latin Core List 2025_LOCAL_LIST",
    "olimpi_via_periculosa": "Olimpi, Via Periculosa_TEXT",
    "wheelock_latin_exercitationes": "Wheelock Latin, Exercitationes_TEXT",
    "terence_adelphoe": "Terence, Adelphoe_TEXT",
    "livy_ab_urbe_condita_ib_selections": "Livy, Ab Urbe Condita IB Selections_Text",
    "cicero_divinatio_in_quintum_caecilium": "Cicero, Divinatio in Quintum Caecilium_TEXT",
    "vergil_aeneid_2025_ap_selections": "Vergil, Aeneid (2025 AP Selections)_LOCAL_TEXT",
    "fabulae_ab_urbe_condita_sandford-scott": "Fabulae Ab Urbe Condita (Sandford-Scott)_TEXT",
    "claudian_de_bello_gothico": "Claudian, De Bello Gothico",
    "cicero_pro_marcello": "Cicero, Pro Marcello_TEXT",
    "claudian_in_rufinum_prefaces": "Claudian, In Rufinum (Prefaces)_TEXT",
    "cicero_pro_fonteio_excluding_fragments": "Cicero, Pro Fonteio (excluding fragments)_TEXT",
    "cicero_pro_murena": "Cicero, Pro Murena_TEXT",
    "vergil_aeneid_ap_selections": "Vergil, Aeneid (AP Selections)_LOCAL_TEXT",
    "claudian_panegyricus_de_iii_consulatu_honorii_augusti": "Claudian, Panegyricus de III Consulatu Honorii Augusti_TEXT",
    "puer_romanus": "Puer Romanus_TEXT",
    "caesar_bellum_civile": "Caesar, Bellum Civile_TEXT",
    "plautus_poenulus": "Plautus, Poenulus_TEXT",
    "cicero_pro_marco_tullio": "Cicero, Pro Marco Tullio_TEXT",
    "senatus_consultum_de_bacchanalibus": "Senatus Consultum de Bacchanalibus_TEXT",
    "anthologia_latina_507-518_epitaphs_of_vergil": "Anthologia Latina 507-518 (Epitaphs of Vergil)_TEXT",
    "propertius_elegies": "Propertius, Elegies_TEXT",
    "ovid_halieutica": "Ovid, Halieutica_TEXT",
    "cicero_de_provinciis_consularibus": "Cicero, De Provinciis Consularibus_TEXT",
    "hildegard_of_bingen_symphoniae_2-5_10_11_12_17_19_21_23_64": "Hildegard of Bingen, Symphoniae 2-5, 10, 11, 12, 17, 19, 21, 23, 64_TEXT",
    "cicero_pro_rabirio_postumo": "Cicero, Pro Rabirio Postumo_TEXT",
    "claudian_de_raptu_prosperinae": "Claudian, De Raptu Prosperinae_TEXT",
    "seneca_medea": "Seneca, Medea_TEXT",
    "vulgate_gospel_of_john": "Vulgate, Gospel of John_TEXT",
    "caesar_bellum_gallicum_ap_selections": "Caesar, Bellum Gallicum (AP Selections)_TEXT",
    "ruodlieb_ap_project_selection": "Ruodlieb (AP Project Selection)_TEXT",
    "trotula_de_curis_mulierum_74-78_86-87_167-168_174-178_181-182": "Trotula, De Curis Mulierum (74-78, 86-87, 167-168, 174-178, 181-182)_TEXT",
    "nepos_life_of_hannibal": "Nepos, Life of Hannibal_TEXT",
    "apuleius_apology": "Apuleius, Apology_TEXT",
    "ennodius_carmina_vogel": "Ennodius, Carmina (Vogel)_TEXT",
    "apuleius_metamorphoses": "Apuleius, Metamorphoses_TEXT",
    "elizabeth_jane_weston_epistula_josepho_scaligero": "Elizabeth Jane Weston, Epistula Josepho Scaligero_TEXT",
    "wheelock_latin_sententiae_antiquae": "Wheelock Latin, Sententiae Antiquae_TEXT",
    "lhomond_de_viris_illustribus_1-18_exordium_to_coriolanus": "Lhomond, De Viris Illustribus (1-18 Exordium to Coriolanus)_TEXT",
    "cicero_pro_caecina": "Cicero, Pro Caecina_TEXT",
    "passio_santarum_perpetuae_et_felicitatis": "Passio santarum Perpetuae et Felicitatis_TEXT",
    "apuleius_de_deo_socratis_prologue": "Apuleius, De Deo Socratis Prologue_TEXT",
    "nepos_life_of_hamilcar": "Nepos, Life of Hamilcar_TEXT",
    "ovid_amores": "Ovid, Amores_TEXT",
    "50_most_common_latin_verbs": "50 Most Common Latin Verbs_LIST",
    "elizabeth_jane_weston_parthenica": "Elizabeth Jane Weston, Parthenica_TEXT",
    "makin_descriptio_pennsylvaniae": "Makin, Descriptio Pennsylvaniae_TEXT",
    "williams_rena_rhinoceros": "Williams, Rena Rhinoceros_TEXT",
    "elizabeth_jane_weston_ad_michaelem_pecka": "Elizabeth Jane Weston, Ad Michaelem Pecka_TEXT",
    "elizabeth_jane_weston_poemata": "Elizabeth Jane Weston, Poemata_TEXT",
    "claudian_panegyricus_de_vi_consulatu_honorii_augusti": "Claudian, Panegyricus de VI Consulatu Honorii Augusti_TEXT",
    "cicero_in_catilinam_1-4": "Cicero, In Catilinam 1-4_TEXT",
    "lucretius_de_rerum_natura": "Lucretius, De Rerum Natura_TEXT",
    "ovid_ars_amatoria": "Ovid, Ars Amatoria_TEXT",
    "pliny_the_younger_panegyricus": "Pliny the Younger, Panegyricus",
    "diederich_frequency_list_poetry": "Diederich Frequency List (Poetry)_LIST",
    "pervigilium_veneris": "Pervigilium Veneris_TEXT",
    "cicero_somnium_scipionis_9-29": "Cicero, Somnium Scipionis 9-29_TEXT",
    "cicero_in_verrem_actio_secunda": "Cicero, In Verrem Actio Secunda_TEXT",
    "florus_epitome_212_catiline": "Florus, Epitome 2.12 (Catiline)_TEXT",
    "elizabeth_jane_weston_elegia_consolatoria_ad_havlik": "Elizabeth Jane Weston, Elegia Consolatoria ad Havlik_TEXT",
    "pseudo-caesar_bellum_africanum": "Pseudo-Caesar, Bellum Africanum_TEXT",
    "seneca_ad_lucilium_epistulae_morales": "Seneca, Ad Lucilium Epistulae Morales_TEXT",
    "cicero_pro_flacco": "Cicero, Pro Flacco_TEXT",
    "seneca_de_ira": "Seneca, De Ira_TEXT",
    "epitaph_of_allia_potestas_cil_637966": "Epitaph of Allia Potestas (CIL 6.37966)_TEXT",
    "seneca_de_brevitate_vitae": "Seneca, De Brevitate Vitae_TEXT",
    "eutropius_breviarium_book_1_beyer": "Eutropius, Breviarium Book 1 (Beyer)_LOCAL_TEXT",
    "horace_epistulae": "Horace, Epistulae_TEXT",
    "cicero_de_imperio_pompei": "Cicero, De Imperio Pompei_TEXT",
    "luchnig_an_introduction_to_ancient_greek_a_literary_approach": "Luchnig, an Introduction to Ancient Greek, a Literary Approach_LIST",
    "sophocles_ajax": "Sophocles, Ajax_TEXT",
    "perseus_greek_stopwords_list": "Perseus Greek Stopwords List_LIST",
    "homer_iliad": "Homer, Iliad_TEXT",
    "athenaze_an_introduction_to_ancient_greek": "Athenaze, an Introduction to Ancient Greek_LIST",
    "dcc_greek_core_list": "DCC Greek Core List_LIST",
    "apollonius_argonautica_book_4": "Apollonius, Argonautica Book 4_TEXT",
    "hansen_quinn_greek_an_intensive_course": "Hansen & Quinn, Greek an Intensive Course_LIST",
    "thucydides_history_of_the_peloponnesian_war": "Thucydides, History of the Peloponnesian War_TEXT",
    "demonsthenes_against_neaira": "Demonsthenes, Against Neaira_LOCAL_TEXT",
    "homer_core_list_frequency_categories_1-4": "Homer Core List Frequency Categories 1-4_LIST",
    "herodotus_book_1": "Herodotus, Book 1_LOCAL_TEXT",
    "sophocles_electra": "Sophocles, Electra_TEXT",
    "herodotus_book_1_high_frequency_vocabulary_list": "Herodotus Book 1 High Frequency Vocabulary List_LIST",
    "plato_euthyphro": "Plato, Euthyphro_TEXT",
    "aesop_fables": "Aesop, Fables_TEXT",
    "homeric_hymn_to_demeter": "Homeric Hymn to Demeter_TEXT",
    "lysias_on_the_murder_of_eratosthenes": "Lysias, On The Murder of Eratosthenes_TEXT",
    "mastronarde_introduction_to_attic_greek": "Mastronarde, Introduction to Attic Greek_LIST",
    "lysias_against_simon": "Lysias, Against Simon_TEXT",
    "sophocles_antigone": "Sophocles, Antigone_TEXT",
    "homer_odyssey": "Homer, Odyssey_TEXT",
    "jact_reading_greek": "JACT, Reading Greek_LIST",
    "aeschylus_prometheus_bound": "Aeschylus, Prometheus Bound_TEXT",
    "keller_russell_learn_to_read_greek": "Keller & Russell, Learn to Read Greek_LIST",
    "national_collegiate_greek_exam_core_list": "National Collegiate Greek Exam Core List_LIST",
    "groton_from_alpha_to_omega": "Groton, From Alpha to Omega_LIST"
}