#services:
#  web:
#    build: .
#    volumes:
#      - .:/app
#    ports:
#      - "5000:5000"


version: '3.3'
services:
  web:
    build: .
    command: uvicorn main:app --host=0.0.0.0 --port=${PORT:-5001} --reload
    volumes:
      - /srv/FastBridge/FastBridgeApp:/app/FastBridgeApp
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    network_mode: host

  
